### ISSUE TITLE
Version 0.1.0 No module named 'vnpy.trader.locale'

### ISSUE THREAD

**Issue by 292427558** [veighna-global/vnpy_evo#36]
Traceback (most recent call last):
  File "G:\project\vnpy\vnpy\examples\veighna_trader\run.py", line 9, in <module>
    from vnpy_evo.trader.ui import MainWindow, create_qapp
  File "D:\ProgramData\Anaconda3\envs\3_10\lib\site-packages\vnpy_evo\trader\ui\__init__.py", line 2, in <module>
    from .mainwindow import MainWindow
  File "D:\ProgramData\Anaconda3\envs\3_10\lib\site-packages\vnpy_evo\trader\ui\mainwindow.py", line 16, in <module>
    from vnpy.trader.locale import _
ModuleNotFoundError: No module named 'vnpy.trader.locale'

**Comment by misska1** [comment]
+1

**Comment by KandyYe** [comment]
Using the "dev" branch of vnpy.

**Comment by veighna-global** [comment]
vnpy v3.9.1 has been released, please try again using:

`pip install vnpy --upgrade`
