### ISSUE TITLE
pyside6.7 still have 'TickMonitor' object has no attribute 'NoEditTriggers'. Did you mean: 'editTriggers'? #39

### ISSUE THREAD

**Issue by linhertz** [veighna-global/vnpy_evo#42]
PS D:\Veighna_Crypto> pip install pyside6
Requirement already satisfied: pyside6 in d:\veighna_station\lib\site-packages (6.7.0)
Requirement already satisfied: shiboken6==6.7.0 in d:\veighna_station\lib\site-packages (from pyside6) (6.7.0)
Requirement already satisfied: PySide6-Essentials==6.7.0 in d:\veighna_station\lib\site-packages (from pyside6) (6.7.0)
Requirement already satisfied: PySide6-Addons==6.7.0 in d:\veighna_station\lib\site-packages (from pyside6) (6.7.0)
PS D:\Veighna_Crypto> python .\run.py

[1;33m📢 Tips:[0m QFluentWidgets Pro is now released. Click [1;96mhttps://qfluentwidgets.com/pages/pro[0m to learn more about it.

The datafeed to be used is not configured. Please modify the datafeed settings in the global configuration.
Traceback (most recent call last):
  File "D:\Veighna_Crypto\run.py", line 32, in <module>
    main()
  File "D:\Veighna_Crypto\run.py", line 25, in main
    main_window = MainWindow(main_engine, event_engine)
  File "D:\veighna_station\lib\site-packages\vnpy_evo\trader\ui\mainwindow.py", line 56, in __init__
    self.init_ui()
  File "D:\veighna_station\lib\site-packages\vnpy_evo\trader\ui\mainwindow.py", line 65, in init_ui
    self.init_widgets()
  File "D:\veighna_station\lib\site-packages\vnpy_evo\trader\ui\mainwindow.py", line 80, in init_widgets
    widget: QtWidgets.QWidget = widget_class(self.main_engine, self.event_engine)
  File "D:\veighna_station\lib\site-packages\vnpy_ctastrategy\ui\widget.py", line 39, in __init__
    self.init_ui()
  File "D:\veighna_station\lib\site-packages\vnpy_ctastrategy\ui\widget.py", line 79, in init_ui
    self.log_monitor: LogMonitor = LogMonitor(self.main_engine, self.event_engine)
  File "D:\veighna_station\lib\site-packages\vnpy\trader\ui\widget.py", line 236, in __init__
    self.init_ui()
  File "D:\veighna_station\lib\site-packages\vnpy_ctastrategy\ui\widget.py", line 424, in init_ui
    super(LogMonitor, self).init_ui()
  File "D:\veighna_station\lib\site-packages\vnpy\trader\ui\widget.py", line 242, in init_ui
    self.init_table()
  File "D:\veighna_station\lib\site-packages\vnpy\trader\ui\widget.py", line 255, in init_table
    self.setEditTriggers(self.NoEditTriggers)
AttributeError: 'LogMonitor' object has no attribute 'NoEditTriggers'. Did you mean: 'editTriggers'?

**Comment by xichangyinwei** [comment]
我也遇到了相同问题，无法运行呢

**Comment by dimicey** [comment]
试试
pip install PySide6==6.3.0

**Comment by Edward-WZ** [comment]
> pip install PySide6==6.3.0

这个就装不上，，，

**Comment by ChunYue0** [comment]
PySide6的版本必须是6.3.0才能兼容，因为好像PySide6后续的版本改动比较大，对vnpy_evo的ui代码不太兼容了，我也有这个问题，但我修改PySide6版本后就解决了！

**Comment by veighna-global** [comment]
当前0.3.0版本的Evo，已经修复了UI图形界面部分代码，对于NoEditTriggers之类老版本枚举值的引用方式，解决了上述问题，请安装最新版本测试。
