### ISSUE TITLE
ModuleNotFoundError: No module named 'loguru' 报错

### ISSUE THREAD

**Issue by linhertz** [veighna-global/vnpy_evo#58]
PS C:\Vnpy_evo_Trading> python .\run.py
Traceback (most recent call last):
  File "C:\Vnpy_evo_Trading\run.py", line 2, in <module>
    from vnpy_evo.trader.engine import MainEngine
  File "C:\veighna_studio\lib\site-packages\vnpy_evo-0.3.0-py3.10.egg\vnpy_evo\trader\engine.py", line 6, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
PS C:\Vnpy_evo_Trading>

各种奇怪的错误

**Comment by linhertz** [comment]
pip install loguru

可以解决这个错误

**Comment by veighna-global** [comment]
已经在setup.cfg中添加对loguru的依赖，后续会自动安装
